apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-logs-pv
spec:
  capacity:
    storage: 1Gi  # Adjust this size based on your needs
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard  # This should match the storage class used by your PVC
  hostPath:
    path: "/mnt/data/airflow-logs"  # Adjust this path based on your node's file system
