apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-logs-pv
spec:
  capacity:
    storage: 1Gi  # Ensure this matches the request in your PVC
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard  # This should match the storage class used by your PVC
  hostPath:
    path: "/mnt/data/airflow-logs"  # Adjust this to a suitable path on your nodes
