fernetKey: R1h4YnBGS3VuUEpOMTdHVWM5cHgyZ3ZGUEVTSTV5Vko=
webserverSecretKey: R1h4YnBGS3VuUEpOMTdHVWM5cHgyZ3ZGUEVTSTV5Vko=
executor: "KubernetesExecutor"

dags:
  gitSync:
    enabled: true
    repo: https://github.com/van-essa/kubernetes_for_data_engineering.git
    branch: main
    rev: HEAD
    depth: 1
    maxFailures: 0
    subPath: "dags"

logs:
  persistence:
    enabled: true  # Enables persistent storage for logs
    size: 1Gi  # Adjust size as needed
    storageClassName: "standard"  # Change based on your Kubernetes storage class

  remoteLogging: false  # Set to true if using remote log storage like S3 or GCS
  remoteBaseLogFolder: ""  # Specify your S3 or GCS bucket path if remoteLogging is true
  remoteLogConnId: ""  # Airflow connection ID for remote log storage
