fernetKey: R1h4YnBGS3VuUEpOMTdHVWM5cHgyZ3ZGUEVTSTV5Vko=
webserverSecretKey: R1h4YnBGS3VuUEpOMTdHVWM5cHgyZ3ZGUEVTSTV5Vko=
executor: "KubernetesExecutor"

dags:
  gitSync:
    enabled: true
    repo: https://github.com/van-essa/kubernetes_for_data_engineering.git
    branch: main
    rev: HEAD
    depth: 1
    maxFailures: 0
    subPath: "dags"
    mountPath: /opt/airflow/dags
